/*
 * Copyright © 2019-2021 CDK8S (cdk8s@qq.com)
 * All rights reserved.
 * 文件名称：GlobalConstant.java
 * 项目名称：sculptor-boot-common-constant
 * 项目描述：公共工具
 * 版权说明：本软件属CDK8S所有
 */

package com.cdk8s.sculptor.constant;


public interface GlobalConstant {

	int SERIOUS_PERFORMANCE_PROBLEMS_TIME_THRESHOLD = 4000;
	int GENERAL_PERFORMANCE_PROBLEMS_TIME_THRESHOLD = 3000;
	int NEED_OPTIMIZE_TIME_THRESHOLD = 2000;


	Integer PAGE_NUM = 1;
	Integer PAGE_SIZE = 10;

	String HOT_SEARCH_DAY_KEY_PREFIX = "HOT_SEARCH:DAY:";
	String HOT_SEARCH_WEEK_KEY_PREFIX = "HOT_SEARCH:WEEK:";
	String HOT_SEARCH_MONTH_KEY_PREFIX = "HOT_SEARCH:MONTH:";
	String HOT_SEARCH_YEAR_KEY_PREFIX = "HOT_SEARCH:YEAR:";

	String USER_AGENT = "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.80 Safari/537.36";

	String REDIS_VOD_KEY_PREFIX = "VOD:CIPHER_TEXT:";

	String DEFAULT_REDIS_CACHE_KEY_PREFIX = "SPRING_CACHE:DEFAULT:";
	String HEADER_TOKEN_KEY = "x-token";
	String MULTI_HEADER_TOKEN_KEY = "multi-token";
	String REDIS_MANAGEMENT_CLIENT_ACCESS_TOKEN_KEY_PREFIX = "OAUTH:MANAGEMENT_CLIENT:ACCESS_TOKEN:";
	Long MOBILE_TOKEN_MAX_TIME_TO_LIVE_IN_SECONDS = 604800L;


	Long NEW_USER_INTERVAL_TIME_MILLISECOND = 604800000L;


	Long DEFAULT_VALIDATE_CODE_EXPIRE_TIME_SECOND = 180L;


	Long DEFAULT_SMS_CODE_EXPIRE_TIME_SECOND = 180L;

	String WEIXIN_QR_LOGIN_STATE_KEY_PREFIX = "WEIXIN_QR_LOGIN:STATE:";

	String REDIS_VALIDATE_CODE_KEY_PREFIX = "VALIDATE_CODE:DEVICE_ID:";
	String REDIS_LOGIN_USERNAME_VALIDATE_CODE_KEY_PREFIX = "VALIDATE_CODE:LOGIN_USERNAME:";

	String TOP_ADMIN_USERNAME = "admin";
	Long TOP_TENANT_ID = 1L;
	Long TOP_ADMIN_USER_ID = 111111111111111111L;
	Long TOP_ADMIN_EMPLOYEE_ID = 111111111111111111L;

	String TOP_ADMIN_ROLE_CODE = "top_admin_role";
	Long TOP_ADMIN_ROLE_ID = 111111111111111111L;

	String TOP_ADMIN_DEPT_CODE = "top_admin_dept";
	Long TOP_ADMIN_DEPT_ID = 111111111111111111L;

	Long TOP_PARENT_ID = 1L;
	String DEFAULT_USER_PASSWORD = "123456";
	Integer MAX_RANKING = 100;

	Long CREATE_USER_DEFAULT_ROLE_ID = 333333333333333333L;
	Long CREATE_USER_DEFAULT_DEPT_ID = 333333333333333333L;

	String JSON_MEDIA_TYPE = "application/json; charset=utf-8";
	String UTF_8 = "UTF-8";

	String CACHE_NULL_VALUE = "is empty";
	int CACHE_TIME_OUT_BY_NULL = 30;

	String THIRD_API_HEADER_APP_KEY = "appKey";
	String THIRD_API_HEADER_EPOCH_MILLI = "epochMilli";
	Long THIRD_API_EPOCH_MILLI_EXPIRE_TIME_SECOND = 300L;
	String THIRD_API_HEADER_SHA_STRING = "shaString";
	String THIRD_API_APP_KEY_1 = "p5v9syzeez5uh7o23y";
	String THIRD_API_APP_SECRET_1 = "36lekpo1187btliwpdjo7nlp2porw5sp";

	String DEFAULT_LOGIN_PAGE_CLIENT_INFO_KEY = "oauthClient";
	String USER_TYPE_ENUM_MAP_KEY = "userTypeEnum";
	String TENANT_ID_MAP_KEY = "tenantId";

	String DEFAULT_LOGIN_PAGE_PATH = "login";
	String DEFAULT_LOGIN_ERROR_KEY = "errorMsg";
	String DEFAULT_LOGOUT_PAGE_PATH = "logoutSuccess";
	String REDIRECT_URI_PREFIX = "redirect:";
	String HTTP_HEADER_USER_AGENT = "User-Agent";

	String OAUTH_TGC_PREFIX = "TGC-";
	String OAUTH_CODE_PREFIX = "OC-";
	String OAUTH_ACCESS_TOKEN_PREFIX = "AT-";
	String OAUTH_REFRESH_TOKEN_PREFIX = "RT-";

	String REDIS_TGC_KEY_PREFIX = "OAUTH:TGC:";
	String REDIS_CLIENT_ID_KEY_PREFIX = "OAUTH:CLIENT_ID:";
	String REDIS_OAUTH_CODE_PREFIX_KEY_PREFIX = "OAUTH:CODE:";
	String REDIS_OAUTH_ACCESS_TOKEN_KEY_PREFIX = "OAUTH:ACCESS_TOKEN:";
	String REDIS_OAUTH_REFRESH_TOKEN_KEY_PREFIX = "OAUTH:REFRESH_TOKEN:";
	String REDIS_OAUTH_USER_INFO_KEY_PREFIX = "OAUTH:USER_INFO:";

	String OAUTH_TOKEN_TYPE = "Bearer";
	String OAUTH_TOKEN_TYPE_UPPER_PREFIX = "Bearer ";
	String OAUTH_TOKEN_TYPE_LOWER_PREFIX = "bearer ";
	String BASIC_AUTH_UPPER_PREFIX = "Basic ";
	String BASIC_AUTH_LOWER_PREFIX = "basic ";

	String HTTP_HEADER_AUTHORIZATION = "Authorization";
	String OAUTH_SERVER_COOKIE_KEY = "x-tgc";
	String OAUTH_CODE_RESPONSE_TYPE = "code";
	String OAUTH_STATE_KEY = "state";
	String OAUTH_TOKEN_RESPONSE_TYPE = "token";
	String OAUTH_ACCESS_TOKEN_KEY = "access_token";
	String OAUTH_REFRESH_TOKEN_KEY = "refresh_token";
	String OAUTH_TOKEN_TYPE_KEY = "token_type";
	String OAUTH_EXPIRES_IN_KEY = "expires_in";
	String OAUTH_ACCESS_TOKEN_TYPE_HINT = "access_token";

	String OAUTH_REFRESH_TOKEN_GRANT_TYPE = "refresh_token";
	String OAUTH_CODE_GRANT_TYPE = "authorization_code";
	String OAUTH_CLIENT_GRANT_TYPE = "client_credentials";
	String OAUTH_TOKEN_GRANT_TYPE = "token";
	String OAUTH_PASSWORD_GRANT_TYPE = "password";
	String OAUTH_USER_ID_GRANT_TYPE = "user_id";

	String OAUTH_ERROR_URI_MSG = "See the full API docs at https://github.com/cdk8s";
	String OAUTH_ERROR_MSG = "invalid request";


}
