FROM java:openjdk-8-jre-alpine

WORKDIR /home

COPY ./deploy/*.jar /home

ENTRYPOINT java -jar *.jar ${JAVA_OPTS} --SPRING_PROFILES_ACTIVE=${SPRING_PROFILES_ACTIVE} --SPRING_REDIS_HOST=${SPRING_REDIS_HOST}
